package com.schwarzit.lovenpark.signal

const val HIDE_MAP_INFO = "hide"
const val LOCATION = "location"
const val KEY = "requestLocation"
const val LATITUDE = "latitude"
const val LONGITUDE = "longitude"
const val REQUEST_PHOTO_URIS = "requestPhotoURIs"
const val PHOTO_URIS = "photoURIs"
const val URIS = "URIs"
const val DATETIME = "date_time"
const val CATEGORY = "category"
const val DESCRIPTION = "description"
const val TAG = "CameraXFragment"
const val FILENAME_FORMAT = "yyyy-MM-dd-HH-mm-ss-SSS"
const val MAP_SIGNAL_SCREENSHOT = "mapSignalScreenshot"
const val MAP_SIGNAL_SCREENSHOT_KEY = "requestMapSignalScreenshot"
const val FILE_EXTENSION = ".jpg"
const val PHOTOS_MAX_NUMBER = 5
const val PHOTOS_MIN_NUMBER = 1
const val LP_SIGNAL = "LP_Signal"
const val SPAN_COUNT = 3
const val MEDIA_DOCUMENTS = "com.android.providers.media.documents"
const val COLUMN = "_data"
const val FILE = "file"
const val CONTENT = "content"
const val TYPE = "image"
const val ORIENTATION_ROTATE_90 = 90F
const val ORIENTATION_ROTATE_180 = 180F
const val ORIENTATION_ROTATE_270 = 270F
const val DST_WITH_HEIGHT = 200
const val SCALE = 0.5
const val REQUIRED_SIZE = 800
const val QUALITY = 80
const val SIGNAL_CONFIRM_DIALOG_TAG = "signal confirm dialog"
const val SIGNAL_ARE_YOU_SURE_POP_UP_TAG = "signal are you sure pop up"
const val REQUEST_PHOTO_PERMISSIONS = "requestPhotoPermissions"
const val PHOTO_PERMISSIONS = "photo_permissions"
const val CAMERA_PERMISSION_DIALOG_TAG = "camera permission dialog"
const val SIGNAL_CONFIRMATION_DIALOG_TAG = "camera permission dialog"
const val SIGNAL_REJECTION_DIALOG_TAG = "signal rejection dialog"
const val IS_USER_IN_PARK = "is user in park"
const val IS_USER_IN_PARK_KEY = "request_is user in park"